apiVersion: v2
appVersion: 0.23.0
description: Creates diagrams from textual descriptions
home: https://kroki.io/
icon: https://raw.githubusercontent.com/yuzutech/kroki.io/master/assets/favicon-196x196.png
maintainers:
  - name: sebastien-prudhomme
    email: sebastien.prudhomme@gmail.com
name: kroki
sources:
  - https://github.com/yuzutech/kroki
  - https://github.com/cowboysysop/charts/tree/master/charts/kroki
version: 5.0.1
dependencies:
  - name: common
    version: 2.9.0
    repository: https://charts.bitnami.com/bitnami/
annotations:
  kubeVersion: ">=1.24"
